### ISSUE TITLE
Multiple identifiers with implicit multiplication

### ISSUE THREAD

**Issue by ericluap** [kevinbarabash/math-parser#62]
In the demo, if you input '2xy' it returns 2 multiplied by the identifier 'xy' instead of 2 multiplied by x multiplied by y. This would make something like dividing both sides by y very difficult.

**Comment by k4b7** [comment]
Right now implicit multiplication between variables requires a space between them.  I was thinking of adding an option so that the space wouldn't be necessary.  In that situation though you'd probably want things like `sin`, `cos`, etc. to be treated a single identifiers and not `s * i * n` so there would be additional work to check the identifier before splitting it up.

**Comment by evykassirer** [comment]
Hmm does mathjs do this with its parser? If so we should probably get this parser to behave that way too

**Comment by k4b7** [comment]
I believe that it requires spaces between things.  I can double check that later today.  The reason why I'd like this to be configurable is that other things like KAS split up contiguous strings into implicit multiplication so having a single parser capable of both seems beneficial for wider adoption.

**Comment by evykassirer** [comment]
oh yeah, I'm pretty sure it does too. e.g. `distance * velocity` should parse those as symbols and not `d*i*s*...`

I guess the idea is users would see it was parsed as a single symbol and add a space or * to fix it themselves :)
